### ISSUE TITLE
USER STORY: MILDEW PREDICTION

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/mildew-detector#10]
As a **client** I can **upload an image of a cherry tree leaf** so that **I can get an indication of whether it is infected or healthy**.

### Acceptance Criteria: 

* Create 'Mildew Detector' page allowing client to upload an image, see the results and download a report.

### Tasks:

- [x] Create model, train and save.
- [x] Add code to /src for use on streamlit dashboard.
- [x] Add code to 'Mildew Detector' page.
- [x] Test with healthy and infected leaves.
---
