### ISSUE TITLE
TASK: SUCCESS MEASURE

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/mildew-detector#15]
Understand the success criteria.

### Tasks:
Success criteria have been outlined in the supplied documentation.
- [x] Client requests image investigation displayed on dashboard.
- [x] Client requires model of 97% accuracy or above.
- [x] Client requires a page to predict if a leaf is infected, with downloadable report.

---
