### ISSUE TITLE
TASK: CLEAN AND AUGMENT DATA

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/mildew-detector#20]
Remove non-image files and augment data to expand available dataset.

### Tasks:

- [x] Check for and remove any non image files.
- [x] Augment Data with ImageDataGenerator
- [x] Save class indices

---
