### ISSUE TITLE
TASK: REFORMAT AND ANNOTATE DATA

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/mildew-detector#21]
Convert images to a shape that can be used in a neural network.
Create labels from folders.

### Tasks:

- [x] Determine average shape.
- [x] Save image shape as pkl.
- [x] Save image labels.

---
