### ISSUE TITLE
TASK: VALIDATE AND TEST

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/mildew-detector#26]
Validate the model and test.

### Tasks:

- [x] Predict on new data.
- [x] Check evaluate accuracy meets criteria (97%)
- [x] Check image samples on dashboard.

---
