### ISSUE TITLE
USER STORY: AVERAGE AND VARIABILITY IMAGES

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/mildew-detector#6]
As a **client** I can **visually differentiate a healthy from an infected leaf** so that **I can visually determine if leaves are infected or not**.

### Acceptance Criteria: 

* Display average and variability images on Leave Visualiser page.

### Tasks:

- [x] Load images into array
- [x] Load image shapes and labels into array
- [x] Plot and save mean and variability of images per label
- [x] Display on Streamlit page
---
