### ISSUE TITLE
USER STORY: AVERAGE LEAF IMAGES

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/mildew-detector#7]
As a **client** I can **view the difference between average healthy and infected leaves** so that **I can compare leaves**.

### Acceptance Criteria: 

* Display average infected and healthy leaf images on dashboard Leaves Visualiser page.

### Tasks:

- [x] Calculate image shape
- [x] Load images into array
- [x] Load image shapes and labels into array
- [x] Plot and save average infected and healthy leaf images
- [x] Display on Streamlit page
---
